[[neo4j-etl-cli]]
== neo4j-etl Command Line Tool

This is the command line tool you use to retrieve and map the metadata from your relational database and drive the export from the relational and import into Neo4j database.

Also, with the newly released user interface you can preview the resulting graph data model and eventually improve it by setting your favourite label and property names
or relationships and property types.

It supports all relational databases with a JDBC driver, for example *MySQL*, *PostgreSQL*, *Oracle* and *Microsoft SQL*.

You can get the http://github.com/neo4j-contrib/neo4j-etl/releases/latest[latest version of the import tool from GitHub].

Once downloaded and uncompressed the operating system specific `zip` / `tar.gz`, you also need download the proper JDBC Driver and add it to the `lib` folder.

You can follow the proper link in the below table in order to download the proper driver jar

|===
|Vendor |JDBC Driver URL

|https://www.mysql.com/[MySql]
|http://dev.mysql.com/downloads/connector/j/

|http://www.postgresql.com/[PostgreSql]
|https://jdbc.postgresql.org/download.html

|https://www.oracle.com/[Oracle]
|http://www.oracle.com/technetwork/database/features/jdbc/default-2280470.html
|https://www.microsoft.com/en-us/sql-server/[Microsoft SQL Server]
|https://www.microsoft.com/en-us/download/details.aspx?id=55539
|===

NOTE: For very large databases make sure to have enough disk-space for the CSV export and the Neo4j datastore and enough RAM and CPUs to finish the import quickly.

=== Available commands

=== 'help' command

----
include::neo4j-etl-help.txt[]
----

=== 'generate-metadata-mapping' command

----
include::neo4j-etl-generate-metadata-mapping.txt[]
----

=== 'export' command

----
include::neo4j-etl-export.txt[]
----

== Example Session: Basic

=== Generate Metadata Mapping

----
export NEO4J_HOME=/path/to/neo4j-enterprise-3.3.0

mkdir -p /tmp/northwind

$NEO4J_HOME/bin/neo4j-etl generate-metadata-mapping \
  --rdbms:url jdbc:oracle:thin:@localhost:49161:XE \
  --rdbms:user northwind --rdbms:password northwind \
  --rdbms:schema northwind > /tmp/northwind/mapping.json
----

=== Offline Bulk Import via `neo4j-import` tool for initial load (neo4j must be empty)

----
echo '{ "multiline-fields" : "true" }' > /tmp/northwind/options.json

$NEO4J_HOME/bin/neo4j-etl export  \
  --rdbms:url jdbc:oracle:thin:@localhost:49161:XE \
  --rdbms:user northwind --rdbms :password northwind \
  --rdbms:schema northwind \
  --using bulk:neo4j-import \
  --import-tool $NEO4J_HOME/bin  \
  --csv-directory /tmp/northwind \
  --options-file /tmp/northwind/options.json \
  --quote '"' --force
----

.Test Offline Bulk Import result
----
$NEO4J_HOME/bin/neo4j-shell -path $NEO4J_HOME/data/databases/graph.db/ -c 'MATCH (n) RETURN labels(n), count(*);'

# +--------------------------+
# | labels(n)     | count(*) |
# +--------------------------+
# | ["Shipper"]   | 3        |
# | ["Employee"]  | 9        |
# | ["Region"]    | 4        |
# | ["Customer"]  | 93       |
# | ["Territory"] | 53       |
# | ["Product"]   | 77       |
# | ["Supplier"]  | 29       |
# | ["Order"]     | 830      |
# | ["Category"]  | 8        |
# +--------------------------+
# 9 rows
----

=== Online Batch Import via `java-bolt-driver` for incremental load (neo4j can be already populated)

----
echo '{ "multiline-fields" : "true" }' > /tmp/northwind/options.json

$NEO4J_HOME/bin/neo4j-etl export  \
  --rdbms:url jdbc:oracle:thin:@localhost:49161:XE \
  --rdbms:user northwind --rdbms:password northwind \
  --rdbms:schema northwind \
  --using cypher:direct \
  --neo4j:url bolt://localhost:7687 \
  --neo4j:user neo4j --neo4j:password neo4j \
  --import-tool $NEO4J_HOME/bin  \
  --csv-directory /tmp/northwind \
  --options-file /tmp/northwind/options.json \
  --quote '"' --force
----

.Test Online Batch Incremental Import result
----
$NEO4J_HOME/bin/cypher-shell -a bolt://localhost:7687 -u neo4j -p neo4j 'MATCH (n) RETURN labels(n), count(*);'

# +--------------------------+
# | labels(n)     | count(*) |
# +--------------------------+
# | ["Shipper"]   | 3        |
# | ["Employee"]  | 9        |
# | ["Region"]    | 4        |
# | ["Customer"]  | 93       |
# | ["Territory"] | 53       |
# | ["Product"]   | 77       |
# | ["Supplier"]  | 29       |
# | ["Order"]     | 830      |
# | ["Category"]  | 8        |
# +--------------------------+
# 9 rows
----

== Example Session: Docker + Northwind

This example session is based on the Northwind example dataset.

DDL scripts are available here:

- https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/mysql/northwind.sql[MySQL]
- https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/postgresql/northwind.sql[PostgreSQL]
- https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/oracle/northwind.sql[Oracle]
- https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/mssql/northwind.sql[Microsoft SQL]

=== MySQL

Download, start and configure the docker container with MySQL:

----
docker pull mysql

docker run --name neo4j-etl-mysql -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=northwind -e MYSQL_USER=neo4j -e MYSQL_PASSWORD=neo4j -d -p 3306:3306 mysql:latest

docker exec -it neo4j-etl-mysql bash
root@eb6f279fdb88:/# mysql -u root -p
Enter password: admin
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.18 MySQL Community Server (GPL)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> grant all privileges on *.* to 'neo4j'@'%' with grant option;
Query OK, 0 rows affected (0.00 sec)

mysql> quit;
Bye
root@bf99fbc0d31c:/# exit
exit
----

Load the database via the following sql script:
https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/mysql/northwind.sql

----
export NEO4J_HOME=/path/to/neo4j-enterprise-3.2.3

mkdir -p /tmp/northwind

echo '{ "multiline-fields" : "true" }' > /tmp/northwind/options.json

./bin/neo4j-etl export \
  --rdbms:url jdbc:mysql://localhost:5433/northwind?autoReconnect=true&useSSL=false \
  --rdbms:user neo4j --rdbms:password neo4j \
  --import-tool $NEO4J_HOME/bin \
  --options-file /tmp/northwind/options.json \
  --csv-directory /tmp/northwind \
  --destination $NEO4J_HOME/data/databases/graph.db/ \
  --quote '"' --force
----

=== PostgreSQL

Download, start and configure the docker container with PostgreSQL 9.6.2:

----
docker pull postgres

docker run --name neo4j-etl-postgres -e POSTGRES_USER=neo4j -e POSTGRES_PASSWORD=neo4j -d -p 5433:5432 postgres

docker run -it --rm --link neo4j-etl-postgres:postgres postgres psql -h postgres -U neo4j
Password for user neo4j:
psql (9.6.2)
Type "help" for help.

neo4j=# DROP DATABASE IF EXISTS northwind;
neo4j=# CREATE DATABASE northwind WITH OWNER 'neo4j' ENCODING 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';
neo4j=# \q
----

Load the database via the following sql script:
https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/postgresql/northwind.sql[northwind.sql]

----
export NEO4J_HOME=/path/to/neo4j-enterprise-3.2.3

mkdir -p /tmp/northwind

echo '{"multiline-fields":"true"}' > /tmp/northwind/options.json

./bin/neo4j-etl export \
  --rdbms:url jdbc:postgresql://localhost:5433/northwind?ssl=false \
  --rdbms:user neo4j --rdbms:password neo4j \
  --import-tool $NEO4J_HOME/bin \
  --options-file /tmp/northwind/options.json \
  --csv-directory /tmp/northwind \
  --destination $NEO4J_HOME/data/databases/graph.db/ \
  --quote '"' --force
----

=== Oracle

Download, start and configure the docker container with Oracle XE 11g:

----
docker pull wnameless/oracle-xe-11g

docker run --name neo4j-etl-oracle -d -p 49160:22 -p 49161:1521 wnameless/oracle-xe-11g

ssh root@localhost -p 49160
root@localhost's password: admin

Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.9.13-moby x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Mon May  1 17:32:48 2017 from 172.17.0.1

root@692c446a274b:~# wget https://raw.githubusercontent.com/neo4j-contrib/neo4j-etl/master/neo4j-etl-it/src/main/resources/scripts/oracle/northwind.sql

root@692c446a274b:~# sqlplus system/oracle

SQL> CREATE USER northwind IDENTIFIED BY northwind;
SQL> GRANT DBA TO northwind;
SQL> CONN northwind/northwind;
SQL> SET sqlblanklines ON;
SQL> @northwind.sql
SQL> quit;

root@692c446a274b:~# exit

export NEO4J_HOME=/path/to/neo4j-enterprise-3.2.3

mkdir -p /tmp/northwind

echo '{"multiline-fields":"true"}' > /tmp/northwind/options.json

./bin/neo4j-etl export \
  --rdbms:url jdbc:oracle:thin:@localhost:49161:XE \
  --rdbms:user northwind --rdbms:password northwind \
  --rdbms:schema northwind \
  --import-tool $NEO4J_HOME/bin \
  --options-file /tmp/northwind/options.json \
  --csv-directory /tmp/northwind \
  --destination $NEO4J_HOME/data/databases/graph.db/ \
  --quote '"' --force
----

=== Microsoft SQL

Download, start and configure the docker container with Microsoft SQL Server:

----
docker run --name neo4j-etl-mssql -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd!' -p 1433:1433 -d microsoft/mssql-server-linux

----

If you want to connect to Microsoft SQL client console than you can run the following command:
----
docker exec -it northwind-mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Passw0rd!' -d <DATABASE>
----

////

=== Example Session: Employees

This example session is based on the Employees example dataset for { MySQL | PostgreSQL | Oracle }.

TODO ...

=== Example Session: MusicBrainz

This example session is based on the MusicBrainz example dataset for { MySQL | PostgreSQL | Oracle }.

TODO ...

////
